.TH ruptimed 8 "September 20 2022"
.SH NAME
ruptimed \- poor man’s ruptime daemon
.SH SYNOPSIS
.B ruptimed
.RI
.br
.SH DESCRIPTION
This manual page documents briefly the
.B ruptimed
command.
.PP
\fBruptimed\fP is the server collectiong ruptime client data,
and answers ruptime queries.
.SH FILES
/var/spool/ruptime/* data files
.SH SEE ALSO
.BR ruptime (1),
.BR ruptime.conf (5),
.BR defaults (1).
.br
.SH HISTORY
See https://en.wikipedia.org/wiki/Berkeley_r-commands
