#!/bin/sh

if [ -f "$HOME"/.ruptime ]; then
    . "$HOME"/.ruptime
elif [ -f /etc/ruptime/ruptime.conf ]; then
    . /etc/ruptime/ruptime.conf
else
    echo "NO CONFIG FOUND in $HOME/.ruptime or /etc/ruptime/ruptime.conf"
    exit 1
fi

if [ -f "$HOME"/.ruptime.key ]; then
    KEY="$HOME"/.ruptime.key
elif [ -f /etc/ruptime/ruptime.key ]; then
    KEY="/etc/ruptime/ruptime.key"
else
    echo "NO KEY FOUND in $HOME/.ruptime.key or /etc/ruptime/ruptime.key"
    exit 1
fi

if [ "${SERVER}x" = "x" ]; then echo "SERVER not set"; exit 1; fi
if [ "${PORT}x" = "x" ]; then echo "PORT not set"; exit 1; fi
if [ "${HOSTNAMECMD}x" = "x" ]; then echo "HOSTNAMECMD not set"; exit 1; fi

d=$(basename "$0")
if [ "${1}x" = "-ux" ] | [ "${1}x" = "-dx" ]; then
    k=$(eval "$HOSTNAMECMD")
    case "$d" in
	runame)
	    case "$(uname -s)" in
		Linux)
		    s=$(echo $(lsb_release -a 2>/dev/null | grep -v ^Desc | awk '{print $NF}'))
		;;
		Darwin)
		    s=$(echo $(sw_vers 2>/dev/null | awk '{print $NF}'))
		;;
	    esac
	    if [ "${1}x" = "-dx" ]; then
		printf "%-28s %s, %s\n" "$k" "`uname -srm`" "$s"; exit 0
	    else
	    	u=$(printf "%-28s %s, %s\n" "$k" "`uname -srm`" "$s" | mcrypt -f "$KEY" -Fq | base64)
	    fi
	;;
	ruptime)
	    if [ "${1}x" = "-dx" ]; then
	        uptime|sed 's/ days\{0,1\},[[:blank:]]\{1,\}/+/; s/ averages\{0,1\}://; s/ min//;s/,//g'|awk -v h=$(eval "$HOSTNAMECMD") '{$1="";printf "%-28s %s %11s %2s %5s %s %6s %6s %6s\n", h, $2, $3, $4, $5, $6, $7, $8, $9}'; exit 0
	    else
	        u=$(uptime|sed 's/ days\{0,1\},[[:blank:]]\{1,\}/+/; s/ averages\{0,1\}://; s/ min//;s/,//g'|awk -v h=$(eval "$HOSTNAMECMD") '{$1="";printf "%-28s %s %11s %2s %5s %s %6s %6s %6s\n", h, $2, $3, $4, $5, $6, $7, $8, $9}' | mcrypt -f "$KEY" -Fq | base64)
	    fi
	;;
	rsw)
	    if [ "${1}x" = "-dx" ]; then
		printf "%-28s %s\n" "$k" "`/usr/lib/ruptime/sw`"; exit 0
	    else
		u=$(printf "%-28s %s\n" "$k" "`/usr/lib/ruptime/sw`" | mcrypt -f "$KEY" -Fq | base64)
	    fi
	;;
	rhw)
	    echo "NOT IMPLEMENTED YET"; exit 1
	;;
	rbench)
	    # /usr/lib/ruptime/benchmark
	    echo "NOT IMPLEMENTED YET"; exit 1
	;;
	rboot)
	    # /usr/lib/ruptime/chkreboot
	    echo "NOT IMPLEMENTED YET"; exit 1
	;;
	rnet)
	    s=$(ifconfig |grep -v "^ " |grep -v ^$ |grep -v "^lo"|sed s,:.*,, |while read a; do echo -n "$a "; ethtool $a 2>/dev/null |grep -i speed; done |sed "s,.peed:,,")
	    u=$(printf "%-28s %s\n" "$k" "$s" | mcrypt -f "$KEY" -Fq | base64)
	;;
	rdisk)
	    echo "NOT IMPLEMENTED YET"; exit 1
	;;
	rload)
	    s=$(uptime | sed "s/,//g" | awk -v c=$(getconf _NPROCESSORS_ONLN) '{printf "%6.2f\n", $(NF-2)*100/c}')
	    m=$(printf "%6.2f\n" $(free -m -t |tail -1 |awk '{print 100*$3/$2}'))
	    u=$(printf "%-28s %s %s\n" "$k" "$s" "$m" | mcrypt -f "$KEY" -Fq | base64)
	;;
	*)
	    echo "PROTOCOL ERROR"
	    exit 1
	;;
    esac
    echo "$d $u" | nc "$SERVER" "$PORT"
    exit 0
fi

d=$(basename "$0")
(echo xz."$d") |
(nc "$SERVER" "$PORT") |
(base64 -d | mcrypt -d -f "$KEY" -Fq | xz -d 2>/dev/null  || echo "NO DATA FOUND ($?)" 1>&2)
