#!/bin/bash

#source
. /etc/ruptime/ruptime.conf

f=$(getpeername)

#echo $f |grep $ACL >/dev/null
#if [ ! $? = 0 ]; then
#    echo Not allowed
#    echo "$f" >> $SPOOL/unauthorized
#    exit 0
#fi

#echo STARTED > $SPOOL/.started

read CMD ARG
h=$(echo $f| awk '{print $1}')
if [ "${ARG}x" = "x" ]; then
    # only query command, deliver results asked for
    if [ $CMD = "xz.ruptime" ]; then
	(find $SPOOL/ -name "*.ruptime" -mmin +10 -exec cat {} \; |sed "s,up.*,down,g";
	find $SPOOL/ -name "*.ruptime" -mmin -10 -exec cat {} \; |sort) | xz -c | mcrypt -f /etc/ruptime/ruptime.key -Fq | base64 -w0
    fi
    for a in runame rload rnet rsw rboot rbench rhw rdisk rac; do
	if [ $CMD = "xz.$a" ]; then
	    (find $SPOOL/ -name "*.$a" -exec cat {} \; |sort) | xz -c | mcrypt -f /etc/ruptime/ruptime.key -Fq | base64 -w0
	fi
    done
else
    # update/add entry
    for a in ruptime runame rload rnet rsw rboot rbench rhw rdisk rac; do
	if [ $CMD = "$a" ]; then
	    echo "$ARG" | base64 -d | mcrypt -d -f /etc/ruptime/ruptime.key -Fq > "$SPOOL/${h}.${CMD}"
	fi
    done
fi
