#!/bin/bash
for a in dpkg rpm nix snap spack flatpak pip2 pip3 brew zypper; do
    which $a &>/dev/null && (
	case $a in
	    dpkg)
		num=`dpkg -l |grep ^ii |wc -l`
		#num="${num}\n"
		#num="${num}`ls -1 /etc/apt/sources.list.d | sed s/^/\ \ \ \ /g`"
	    ;;
	    rpm)
		# rpm --version | awk '{print $NF}'
		num=`rpm -qa | wc -l`
	    ;;
	    brew)
		num=`brew list| wc -l`
	    ;;
	    pip2)
		num=`pip2 list 2>/dev/null | wc -l`
	    ;;
	    pip3)
		num=`pip3 list 2>/dev/null | wc -l`
	    ;;
	    spack)
		num=`spack find 2>/dev/null |wc -l`
	    ;;
	    snap)
		num=`snap list |sed 1d |wc -l`
	    ;;
	    flatpak)
		num=`flatpak list | wc -l`
	    ;;
	    zypper)
	    	num=`zypper search --installed-only | grep package$ | wc -l`
	    ;;
	    *)
		num="n/a"
	    ;;
	esac
	echo -ne "$a $(echo $num) "
    ) #|| echo "$a not found..."
done
echo
