name: ruptime # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.8' # just for humans, typically '1.2+git' or '1.3.2'
summary: poor man’s ruptime
description: |
 This is a modern implementation of the r-commands developed in 1982.
                                                                                  
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # was devmode use 'strict' once you have the right plugs and slots

apps:
  ruptime:
    command: ruptime

parts:
  stage-packages: [acct, bc, cron, dmidecode, memtester, netcat-openbsd, openssl, xz-utils]
  ruptime:
    plugin: dump
    source: https://github.com/alexmyczko/ruptime.git
#    source-type: tar
#  remote-part:
#    plugin: dump
#    source: https://remote-resource.org/cool-package.deb
#    source-type: deb

# snapcraft login
# snapcraft upload --release=stable ruptime_whatever.snap
